name: MSBuild

on:
  push:
    branches: [ main ]
    paths:
      - 'JanusClient/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'JanusClient/**'        
      - '.github/workflows/**'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
    - name: Restore Packages
      run: nuget restore JanusClient.sln
      working-directory: 'JanusClient/'
    - name: Build Solution
      run: |
        msbuild.exe JanusClient.sln /p:platform="Any CPU" /p:configuration="Release"
      working-directory: 'JanusClient/'
